# 时间日期加减计算测试脚本

name: Delete Date Directory

on:
  workflow_dispatch:
    inputs:
      target_date:
        description: "要删除的日期目录 (格式: YYYY-MM-DD)"
        required: true
        default: "2023-01-01"

jobs:
  delete-directory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Confirm directory structure
      run: |
        ls -l
        
    - name: Delete target directory
      run: |
        DIR_PATH=$(date +'%Y-%m-%d' -d'-10 day')
        echo $DIR_PATH
